# Generated by Django 4.2.1 on 2024-10-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="user",
        ),
    ]
