# Generated by Django 4.2.1 on 2024-10-03 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_remove_todoitem_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todoitem",
            options={
                "ordering": ["-id"],
                "verbose_name": "Todo item",
                "verbose_name_plural": "Todo items",
            },
        ),
        migrations.AddField(
            model_name="todoitem",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_do",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
            preserve_default=False,
        ),
    ]
